#Port Configuration
server:
  port: 8080

#DB Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: MySQL@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: spring-boot-security

#Okta Configuration
okta:
  oauth2:
    issuer: https://dev-41251411.okta.com/oauth2/default
    audience: api://default
    client-id: xxx
    client-secret: xxx
    scopes:
      - openid
      - profile
      - email
      - offline_access